package com.bob.compliance.model;
// Generated 8 Sep, 2016 3:17:01 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "test")
@SuppressWarnings("all")
public class Client implements java.io.Serializable {

	private Integer clientId;
	private String clientName;
	private Boolean isActive;
	private String address;
	private String phone;
	private String emailId;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Client() {
	}

	public Client(String clientName, String emailId) {
		this.clientName = clientName;
		this.emailId = emailId;
	}

	public Client(String clientName, Boolean isActive, String address, String phone, String emailId,
			Set<Contact> contacts) {
		this.clientName = clientName;
		this.isActive = isActive;
		this.address = address;
		this.phone = phone;
		this.emailId = emailId;
		this.contacts = contacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "client_id", unique = true, nullable = false)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "client_name", nullable = false, length = 50)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email_id", nullable = false, length = 50)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
