package com.bob.compliance.model;
// Generated 8 Sep, 2016 3:17:01 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "test")
@SuppressWarnings("all")
public class Role implements java.io.Serializable {

	private String roleName;
	private String roleDesc;
	private Set<Contact> contacts = new HashSet<Contact>(0);
	private Set<RoleScreen> roleScreens = new HashSet<RoleScreen>(0);

	public Role() {
	}

	public Role(String roleName) {
		this.roleName = roleName;
	}

	public Role(String roleName, String roleDesc, Set<Contact> contacts, Set<RoleScreen> roleScreens) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.contacts = contacts;
		this.roleScreens = roleScreens;
	}

	@Id

	@Column(name = "role_name", unique = true, nullable = false, length = 20)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc", length = 200)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RoleScreen> getRoleScreens() {
		return this.roleScreens;
	}

	public void setRoleScreens(Set<RoleScreen> roleScreens) {
		this.roleScreens = roleScreens;
	}

}
