package com.bob.compliance.model;
// Generated 8 Sep, 2016 3:17:01 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleScreen generated by hbm2java
 */
@Entity
@Table(name = "role_screen", catalog = "test")
@SuppressWarnings("all")
public class RoleScreen implements java.io.Serializable {

	private Integer roleScreenId;
	private Role role;
	private Screen screen;

	public RoleScreen() {
	}

	public RoleScreen(Role role, Screen screen) {
		this.role = role;
		this.screen = screen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_screen_id", unique = true, nullable = false)
	public Integer getRoleScreenId() {
		return this.roleScreenId;
	}

	public void setRoleScreenId(Integer roleScreenId) {
		this.roleScreenId = roleScreenId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_name", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_name", nullable = false)
	public Screen getScreen() {
		return this.screen;
	}

	public void setScreen(Screen screen) {
		this.screen = screen;
	}

}
