package com.bob.compliance.model;
// Generated 8 Sep, 2016 3:17:01 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Screen generated by hbm2java
 */
@Entity
@Table(name = "screen", catalog = "test")
@SuppressWarnings("all")
public class Screen implements java.io.Serializable {

	private String screenName;
	private String screenDesc;
	private Set<RoleScreen> roleScreens = new HashSet<RoleScreen>(0);

	public Screen() {
	}

	public Screen(String screenName) {
		this.screenName = screenName;
	}

	public Screen(String screenName, String screenDesc, Set<RoleScreen> roleScreens) {
		this.screenName = screenName;
		this.screenDesc = screenDesc;
		this.roleScreens = roleScreens;
	}

	@Id

	@Column(name = "screen_name", unique = true, nullable = false, length = 20)
	public String getScreenName() {
		return this.screenName;
	}

	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}

	@Column(name = "screen_desc", length = 200)
	public String getScreenDesc() {
		return this.screenDesc;
	}

	public void setScreenDesc(String screenDesc) {
		this.screenDesc = screenDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "screen")
	public Set<RoleScreen> getRoleScreens() {
		return this.roleScreens;
	}

	public void setRoleScreens(Set<RoleScreen> roleScreens) {
		this.roleScreens = roleScreens;
	}

}
