package com.bob.compliance.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* Status generated by hbm2java
*/
@Entity
@Table(name = "status", catalog = "test")
public class Status implements java.io.Serializable {

	private int scode;
	private String message;

	public Status() {
	}

	public Status(int scode) {
		this.scode = scode;
	}

	public Status(int scode, String message) {
		this.scode = scode;
		this.message = message;
	}

	@Id

	@Column(name = "scode", unique = true, nullable = false)
	public int getScode() {
		return this.scode;
	}

	public void setScode(int scode) {
		this.scode = scode;
	}

	@Column(name = "message", length = 150)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
